Repository SonHyeWon/SnakeGame, pull requests merged in 2020-05, with the labels that each got.

#1 [0.0.1] 매크로 변수 수정
  main.c
Labels: mod

#8 [0.2.1] object.h 헤더파일로 전역변수 및 구조체 이동
  main.c
  object.h
Labels: mod, new

#9 [0.2.2] 새로운 구조체 구현
  main.c
  object.c
  object.h
  screen.h
  ui.c
  ui.h
Labels: mod, new

#10 [0.3.3] 헤더파일 추가 및 값을 비교하는 함수 구현
  main.c
  object.c
  object.h
Labels: new
