Repository SonHyeWon/SnakeGame, pull requests merged in 2020-06, with the labels that each got.

#15 [0.3.4] changeDir 함수, isKeyInput 함수 구현 및 사용
  main.c
  ui.c
  ui.h
Labels: mod

#17 [1.2.2] 자가 충돌 체크하는 함수 구현
  object.c
  object.h
Labels: new

#18 [0.3.5] updateBody 및 moveSnake 함수 구현 및 적용
  main.c
  object.c
  object.h
Labels: mod, new

#21 [0.3.6] 뱀과 과일의 충돌 함수화
  object.c
  object.h
Labels: mod

#22 [0.3.1] createFruit 함수 구현 수정
  main.c
  object.c
  object.h
Labels: mod

#23 [0.3.1] createSnake 함수 구현
  main.c
  object.c
  object.h
Labels: mod, new

#24 [0.3.7] clearLine 및 clearGameScreen 함수 생성 및 적용
  main.c
  ui.c
  ui.h
Labels: mod, new

#25 [1.1.1] mapArray 배열 생성
  ui.c
  ui.h
Labels: new

#29 [0.3.1] createFruit 함수 버그 수정
  object.c
Labels: bug

#32 [0.3.3] rightMax 함수 조건 변화 및 swp file 복구 후 삭제
  object.c
Labels: del, mod

#31 [0.3.9] drawObject 함수 구현 및 사용
  main.c
  object.c
  object.h
Labels: mod

#44 [0.4.1] 형식 통일
  main.c
  object.c
  ui.c
Labels: mod

#46 [0.5.1] 머리 주석 추가
  main.c
Labels: del, new
